Merge Hyperdrive content into master
Azure/RNNForTimeSeriesForecasting pull request #9
Opened 2019-05-31 16:48 UTC by vapaunic

This PR would merge the new hyper-parameter with Hyperdrive tuning code into the master.

2019-06-04 17:59 UTC, pechyony requested changes
I added a couple of minor comments. Also, could put into hyperparameter_tuning.ipynb results of runs of all cells. Other than that, PR looks great.

2019-06-04 17:59 UTC, pechyony commented on hyperparameter_tuning/CNN/README.md
> +# Multi-step forecasting with recurrent neural network that generates vector output
replace "recurrent" with "convolutional"

2019-06-04 17:59 UTC, pechyony commented on hyperparameter_tuning/README.md
> +- RNN encoder decoder approach - [rnn_encoder_decoder_config.json](rnn_encoder_decoder_config.json)
Add pointer to JSON file of CNN

2019-06-11 08:36 UTC, vapaunic commented on hyperparameter_tuning/CNN/README.md
> +# Multi-step forecasting with recurrent neural network that generates vector output
Good catch, thanks Dmitry. I'll address these comments.

2019-06-11 12:44 UTC, vapaunic commented
@pechyony , I addressed your comments:
- Fixed up CNN readme wording, and the config file link
- added cell outputs in hyperdrive notebook.

Let me know if you have further comments, @angusrtaylor , @yijingchen , otherwise I'll merge the PR.

2019-06-13 11:36 UTC, merged